services:
- docker
language: generic
before_install:
- docker build -t ${REPOSITORY} .
deploy:
  provider: script
  script: bash docker_push
env:
  global:
  - secure: NGwzkQHp/W3xWw0yRh6rC3u20CjULHABy1MlE0U049FiPhRb6/9g+Zol2H5zsWu/xBJ4b4HbicAdPaSAs+AZjD4mlV7CCjGOqv6WX6yH4mmp/lfUIJ0DkIdRflWw8mCiNhMUo6HXxPpZnw5zizX9WrzsD0TLC6Al8FzFnCTsqWnhEf6xIeauK5nkkY5daIhrpyqAHMYJ5VLj6/PFCvzI9zs1pXSaiD4ve1pLT/mTfBDcK4wDw2nZjRsIMqvJ1D68iM9MRINYc6pdPVlcr8OUgpqfvJQEOH+Z+j9wce64pWQo83iWp8ascLd1oLFVjZEaLpMkrVYyrfWwz1VkrFtngG8e3H056Qrnn/ZgXH5dBxZsb7xH3LIq5VmAlablc3bFMI1Ed8qC2fazEleFT7Qz0w7D1r3FrQbIMoRAlXhpmEvmRh/VjQoS3kebgZjElJ8uSrZHA6dyO3D4ogr562pxNxssKLz5aRZT7ItsYPXbQANurrV6EH5PLyDVeYINcM2qFzbsD9oTl1lIY7ob2giFe4hcXrqiiA6rP219wdZHBdSKzFnkymzW95cgRJAips8VQhYhQUKxHDSr8JCsRzfO0HwWR+U0YA5mIIJ7PDVSV+/SbIGy5J6OgUxfZ+hprciWVCDA+PcV+xgELt8jUpnJruXCo1DoWeGAnin3hWFoxl8=
  - secure: ILI08ZT72zDae7FrlnmUOwepM7bqUZP4OsNpkyXvixLNoP9j0KQPpHGujR18fdharfZBqY5VCLYllSEfi+TNCy0v0z1jl6nzddSZrvDRnwo2vSb3dJrb8ebNktS8sBvt5RzmlmhK4K6v4BpgSG3Fx5hU5dWEOCSH+zzBcgV5zpeNdoj3mmQibg+1oRF1DJazF/lYn3Y+6RxVdtAQn6GXxsKOuEfTTYbrgvskrOGllfLzOOwUFE9XiDOX2WJTTIK3sFeByQyRg5A2P39bhgrj8b6Kqw1eESvf/Es5uU/iljErfBufv/Pr+RdhrY3etOOUas6UoHb1qeE96AyF08ToiSL52WOp4xs6NtAWSYfJE6yKei9wAnQxCzQic9uxo3sorv5VpURaLYteqZ9yRMB5fTqeO2zIl1ysolwx/t4kC3//oGEakIEixX/8OWXIfJcak90IPo8+cLXBy5/LkcZatAvKNaBvdA/3bzlQOIDPqH0WZoVVfu1bTxL28k+tTRIHnTfvV4h5KbibYr8NOOa1pmahfnUwv67rTuJHkylTPvgfVCJh//Pq+UtOmjuKL4G0+Vihp+261qwMbsE+Kc8971n0xcaoaJoV6/avtzEzmf664vtu5wvBMJqcOIn8fWZ2Otx/ck5/vXoKT4BObaQO2G+Hjlmkp4upHsS6CNr9AQk=
